#logo = "/mokksy-mascot-256.png"
uniqueHomePage = false

repo = "https://github.com/mokksy/mokksy.dev"

# Defaults to true if not set
# Enable copyRight Footer Stamp. Takes in attribution
enableCopyright = true
images = ['mokksy-mascot-512.png']

# search
[search]
on = false
global = false # turn to `true` to enable global search

[search.algolia]
enable = true # if false search will default to fusejs

# Site logo
[logo]
lightMode = "mokksy-logo.png"
darkMode = "mokksy-logo.png"

[source]
name = "GitHub"
iconLight = "images/GitHubMarkLight.svg"
iconDark = "images/GitHubMarkDark.svg"
url = "https://github.com/mokksy/mokksy"

[author]
name = "Konstantin Pavlov"
url = "https://kpavlov.me"
