name: Docs to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  JVM_VERSION: 25
  JVM_DISTRIBUTION: temurin

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: docs/public
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 1

      - name: Set up JDK ${{ env.JVM_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: ${{ env.JVM_DISTRIBUTION }}
          cache: gradle

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.158.0'
          extended: true

      - name: Run Knit
        run: make knit

      - name: Build Hugo Site
        run: |
          cd docs
          hugo --minify

      - name: Upload PR artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: site-preview
          path: docs/public

      - name: Upload Pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
