name: Docs to GitHub Pages

on:
  push:
    branches: [ "main" ]
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

env:
  JVM_VERSION: 25
  JVM_DISTRIBUTION: temurin

jobs:
  deploy:

    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up JDK ${{ env.JVM_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: ${{ env.JVM_DISTRIBUTION }}
          cache: gradle

      - name: 🐘Setup Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.158.0'
          extended: true

      - name: Run Knit
        run: |-
          make knit

      - name: Build Hugo Site
        run: |-
          cd docs && \
          hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
